exec(open("main/not/modules.py").read())
exec(open("main/not/create.py").read())
exec(open("main/not/setting.py").read())
exec(open("main/not/log.py").read())
exec(open("main/default.py").read())
exec(open("main/not/view_log.py").read())
exec(open("main/not/admin.py").read())
exec(open("main/not/telegram.py").read())
